### ISSUE TITLE
License adherence

### ISSUE THREAD

**Issue by ollef** [chessai/multihash#1]
Please adhere to the license that the bulk of the code in this repository is licensed under. It can be found [here](https://github.com/ollef/sixten/blob/master/LICENSE).

Cheers!

**Comment by chessai** [comment]
Sorry about that! I used 'cabal init' to generate that, and should have fixed the licensing. I have fixed the licensing in LICENSE and in the .cabal file. Please point out anything you see wrong with the licensing as of now.

**Comment by chessai** [comment]
Keeping this open until you give the OK.

**Comment by ollef** [comment]
No worries, and thanks for fixing it. Looks good! :)
